name: Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup bats
      run: sudo apt-get update && sudo apt-get install -y bats
    - name: Setup Wasmer
      uses: wasmerio/setup-wasmer@v3.1
      with:
        version: 'v4.2.3'
    - name: prepare Onyx
      run: |
        wasmer --version
        git clone https://github.com/onyx-lang/onyx
        cd onyx
        git fetch origin v0.1.9-beta
        git checkout v0.1.9-beta
        source settings.sh
        ./build.sh compile package
        echo $(pwd)"/dist/bin" >> $GITHUB_PATH
        echo $(pwd)"/dist/bin"
        ls $(pwd)"/dist/bin"
        echo "$PATH"
        cd ..
    - name: test
      run: |
        export ONYX_PATH=onyx/dist
        make test
    - name: upload wasi
      uses: actions/upload-artifact@v4
      with:
        name: wasi
        path: onylox.wasm
  release:
    # TODO: only when tagged
    needs: build
    name: Release
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Wasmer
      uses: wasmerio/setup-wasmer@v3.1
      with:
        version: 'v4.2.3'
    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: wasi
    - name: Publish to Wasmer
      run: |
        wasmer login --no-browser $WASMER_TOKEN
        wasmer publish
